# Generated by Django 6.0.2 on 2026-02-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pswd',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='emp_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
