# Generated by Django 6.0.2 on 2026-03-25 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('desig_id', models.AutoField(primary_key=True, serialize=False)),
                ('desig_name', models.CharField(choices=[('Chief Warden', 'Chief Warden'), ('Warden', 'Warden'), ('Care Taker', 'Care Taker')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('hostel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StaffStatus',
            fields=[
                ('staff_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Solved', 'Solved')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('pswd', models.CharField(default='Collage@123', max_length=128)),
                ('desig_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.designation')),
                ('hostel_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grievance.hostel')),
                ('staff_status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.staffstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('pswd', models.CharField(max_length=128)),
                ('mobile', models.CharField(max_length=15)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('Complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('solved_date', models.DateTimeField(blank=True, null=True)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.category')),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.hostel')),
                ('solved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grievance.staff')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.status')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.student')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalWorker',
            fields=[
                ('worker_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievance.category')),
            ],
        ),
    ]
