# Generated by Django 6.0.2 on 2026-03-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
